export { default as Home } from './SearchHome';
export { default as EditInfo } from './EditInfo';
export { default as Mileage } from './Mileage';
export { default as Purchase } from './Purchase';
export { default as Return } from './Return';
export { default as Review } from './Review';
export { default as ReviewWrite } from './ReviewWrite';
export { default as Wish } from './Wish';
export { default as ImgTab } from './ImgTab';